SELECT
    'BANK'                  AS SOURCE,
    S.ACCOUNT,
    NVL(ACC.NAME, NVL(S.ACCOUNT, '-')) AS ACCOUNT_NAME,
    S.SUBACCOUNT,
    NVL(CL.NAME, NVL(S.SUBACCOUNT, '-')) AS CLIENT_NAME,
    S.SUBACCOUNT_TYPE,
    S.BRANCH,
    S.CURRENCY,
    S.OPENBAL_DEBIT,
    S.OPENBAL_CREDIT,
    S.DEBIT,
    S.CREDIT,
    S.ENDBAL_DEBIT,
    S.ENDBAL_CREDIT,
    CAST(NULL AS VARCHAR2(20)) AS NCLIENT,
    CAST(NULL AS NUMBER)       AS AMOUNT,
    CAST(NULL AS NUMBER)       AS TRANS_FLAG,
    S.ENDBAL_DEBIT             AS CONTRIB_TO_BALANCE
FROM MKBD.MAP_BANK MB
INNER JOIN MKBD.MKBD_BALANCE_SUMMARY S ON S.ACCOUNT = MB.NCLIENT
INNER JOIN DENPASAR.ACCOUNT ACC        ON ACC.CODE = S.ACCOUNT
LEFT  JOIN DENPASAR.CLIENT  CL         ON S.SUBACCOUNT = CL.CODE
WHERE S.GEN_DATE         = TO_DATE(:genDate, 'YYYY-MM-DD')
  AND LENGTH(MB.NCLIENT)   = 8
  AND LENGTH(MB.BANK_NAME) = 3
  AND MB.ISCLIENT          = 'N'
  AND ACC.ACCOUNT_TYPE     = (SELECT ID FROM DENPASAR.ACCOUNT_TYPE WHERE NAME = 'BANK')

UNION ALL

SELECT
    'CLIENT_POSITION_207'      AS SOURCE,
    CAST(NULL AS VARCHAR2(20)) AS ACCOUNT,
    '-'                        AS ACCOUNT_NAME,
    CAST(NULL AS VARCHAR2(20)) AS SUBACCOUNT,
    NVL(C.NAME, NVL(AP.NCLIENT, '-')) AS CLIENT_NAME,
    CAST(NULL AS NUMBER)       AS SUBACCOUNT_TYPE,
    CAST(NULL AS VARCHAR2(20)) AS BRANCH,
    CAST(NULL AS VARCHAR2(1))  AS CURRENCY,
    CAST(NULL AS NUMBER)       AS OPENBAL_DEBIT,
    CAST(NULL AS NUMBER)       AS OPENBAL_CREDIT,
    CAST(NULL AS NUMBER)       AS DEBIT,
    CAST(NULL AS NUMBER)       AS CREDIT,
    CAST(NULL AS NUMBER)       AS ENDBAL_DEBIT,
    CAST(NULL AS NUMBER)       AS ENDBAL_CREDIT,
    AP.NCLIENT,
    AP.AMOUNT,
    AP.TRANS_FLAG,
    -ABS(AP.AMOUNT)            AS CONTRIB_TO_BALANCE
FROM MKBD.MKBD_CLIENT_POSITION AP
INNER JOIN DENPASAR.CLIENT C           ON AP.NCLIENT = C.CODE
LEFT  JOIN DENPASAR.CLIENT_PROPERTY CP ON AP.NCLIENT = CP.CLIENT_ID
WHERE AP.TRANS_FLAG = 207
  AND AP.AMOUNT     < 0
  AND AP.GEN_DATE   = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND (LENGTH(NVL(CP.BANK_ACC_NO_INVESTOR, '')) < 1 OR CP.BANK_ACC_NO_INVESTOR IS NULL)
  AND C.CLIENT_TYPE IN (12, 14, 16, 33)

ORDER BY SOURCE, ACCOUNT, NCLIENT