SELECT S.GEN_DATE,
       S.ID,
       S.TRANS_FLAG,
       S.MKBD_FLAG,
       S.ACCOUNT,
       NVL(ACC.NAME, NVL(S.ACCOUNT, '-')) AS ACCOUNT_NAME,
       S.SUBACCOUNT_TYPE,
       S.SUBACCOUNT,
       NVL(CL.NAME, NVL(S.SUBACCOUNT, '-')) AS CLIENT_NAME,
       S.BRANCH,
       S.CURRENCY,
       S.OPENBAL,
       S.DEBIT,
       S.CREDIT,
       S.ENDBAL,
       S.ENDBAL_DEBIT,
       S.ENDBAL_CREDIT,
       S.OPENBAL_DEBIT,
       S.OPENBAL_CREDIT,
       S.CREATED_BY,
       S.CREATED_ON,
       S.CREATED_USING,
       S.UPDATED_BY,
       S.UPDATED_ON,
       S.UPDATED_USING
FROM MKBD.MAP_BANK MB
INNER JOIN MKBD.MKBD_BALANCE_SUMMARY S ON S.ACCOUNT = MB.NCLIENT
INNER JOIN DENPASAR.ACCOUNT ACC        ON ACC.CODE = S.ACCOUNT
LEFT  JOIN DENPASAR.CLIENT  CL         ON S.SUBACCOUNT = CL.CODE
WHERE S.GEN_DATE         = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND LENGTH(MB.NCLIENT)   = 8
  AND LENGTH(MB.BANK_NAME) = 3
  AND MB.ISCLIENT          = 'N'
  AND ACC.ACCOUNT_TYPE     = (SELECT ID FROM DENPASAR.ACCOUNT_TYPE WHERE NAME = 'BANK')

UNION ALL

SELECT M.GEN_DATE,
       M.ID,
       M.TRANS_FLAG,
       M.MKBD_FLAG,
       M.ACCOUNT,
       NVL(A.NAME, NVL(M.ACCOUNT, '-')) AS ACCOUNT_NAME,
       M.SUBACCOUNT_TYPE,
       M.SUBACCOUNT,
       NVL(C.NAME, NVL(M.SUBACCOUNT, '-')) AS CLIENT_NAME,
       M.BRANCH,
       M.CURRENCY,
       M.OPENBAL,
       M.DEBIT,
       M.CREDIT,
       M.ENDBAL,
       M.ENDBAL_DEBIT,
       M.ENDBAL_CREDIT,
       M.OPENBAL_DEBIT,
       M.OPENBAL_CREDIT,
       M.CREATED_BY,
       M.CREATED_ON,
       M.CREATED_USING,
       M.UPDATED_BY,
       M.UPDATED_ON,
       M.UPDATED_USING
FROM MKBD.MKBD_BALANCE_SUMMARY M
LEFT JOIN DENPASAR.ACCOUNT A ON M.ACCOUNT = A.CODE
LEFT JOIN DENPASAR.CLIENT  C ON M.SUBACCOUNT = C.CODE
WHERE M.GEN_DATE        = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND LENGTH(M.ACCOUNT)  = 8
  AND M.MKBD_FLAG        = 0
  AND M.ACCOUNT LIKE '10101%'

UNION ALL

SELECT TO_DATE(:genDate,'yyyy-mm-dd') AS GEN_DATE,
       CAST(NULL AS NUMBER)               AS ID,
       CAST(NULL AS NUMBER)               AS TRANS_FLAG,
       CAST(NULL AS NUMBER)               AS MKBD_FLAG,
       '207 - FINAL BALANCE'              AS ACCOUNT,
       '207 - FINAL BALANCE'              AS ACCOUNT_NAME,
       CAST(NULL AS NUMBER)               AS SUBACCOUNT_TYPE,
       CAST(NULL AS VARCHAR2(20))         AS SUBACCOUNT,
       NVL(C.NAME, NVL(AP.NCLIENT, '-'))  AS CLIENT_NAME,
       CAST(NULL AS VARCHAR2(20))         AS BRANCH,
       CAST(NULL AS VARCHAR2(1))          AS CURRENCY,
       CAST(NULL AS NUMBER)               AS OPENBAL,
       CAST(NULL AS NUMBER)               AS DEBIT,
       CAST(NULL AS NUMBER)               AS CREDIT,
       CAST(NULL AS NUMBER)               AS ENDBAL,
       -SUM(ABS(AP.AMOUNT))               AS ENDBAL_DEBIT,
       CAST(NULL AS NUMBER)               AS ENDBAL_CREDIT,
       CAST(NULL AS NUMBER)               AS OPENBAL_DEBIT,
       CAST(NULL AS NUMBER)               AS OPENBAL_CREDIT,
       CAST(NULL AS VARCHAR2(12))         AS CREATED_BY,
       CAST(NULL AS DATE)                 AS CREATED_ON,
       CAST(NULL AS VARCHAR2(12))         AS CREATED_USING,
       CAST(NULL AS VARCHAR2(12))         AS UPDATED_BY,
       CAST(NULL AS DATE)                 AS UPDATED_ON,
       CAST(NULL AS VARCHAR2(12))         AS UPDATED_USING
FROM MKBD.MKBD_CLIENT_POSITION AP
INNER JOIN DENPASAR.CLIENT C           ON AP.NCLIENT = C.CODE
LEFT  JOIN DENPASAR.CLIENT_PROPERTY CP ON AP.NCLIENT = CP.CLIENT_ID
WHERE AP.TRANS_FLAG = 207
  AND AP.AMOUNT     < 0
  AND AP.GEN_DATE   = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND (LENGTH(NVL(CP.BANK_ACC_NO_INVESTOR, '')) < 1 OR CP.BANK_ACC_NO_INVESTOR IS NULL)
  AND C.CLIENT_TYPE IN (12, 14, 16, 33)
GROUP BY C.NAME, AP.NCLIENT