SELECT R.BANK_NAME AS DESCRIPTION,
       R.NCLIENT,
       NVL(C.NAME, NVL(R.NCLIENT, '-')) AS CLIENT_NAME,
       SUM(R.AMOUNT) AS AMOUNT
FROM MKBD.RDI_BALANCE_HISTORICAL R
LEFT JOIN DENPASAR.CLIENT C ON R.NCLIENT = C.CODE
WHERE R.NCLIENT IS NOT NULL
 AND TRUNC(R.TRANS_DATE) = TO_DATE(:genDate, 'YYYY-MM-DD')
 AND R.BANK_NAME IN ('BCA','CIMB')
GROUP BY R.BANK_NAME, R.NCLIENT, C.NAME

UNION ALL


SELECT 'TOTAL AMOUNT - 207' AS DESCRIPTION,
       AP.NCLIENT,
       NVL(C.NAME, NVL(AP.NCLIENT, '-')) AS CLIENT_NAME,
       SUM(ABS(AP.AMOUNT)) AS AMOUNT
FROM MKBD.MKBD_CLIENT_POSITION AP
         INNER JOIN DENPASAR.CLIENT C ON AP.NCLIENT = C.CODE
         LEFT JOIN DENPASAR.CLIENT_PROPERTY CP ON AP.NCLIENT = CP.CLIENT_ID
WHERE AP.TRANS_FLAG = 207
  AND AP.AMOUNT < 0
  AND AP.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND (LENGTH(NVL(CP.BANK_ACC_NO_INVESTOR, '')) < 1 OR CP.BANK_ACC_NO_INVESTOR IS NULL)
  AND C.CLIENT_TYPE IN (12, 14, 16, 33)
GROUP BY AP.NCLIENT, C.NAME