WITH MF_CLIENTS AS (
    SELECT CODE FROM DENPASAR.CLIENT WHERE SID LIKE 'MF%'
),
BASE_ROWS AS (
    SELECT
        A.ACCOUNT,
        A.SUBACCOUNT,
        A.TRANS_DATE,
        A.TRANS_DUEDATE,
        A.TRANS_PERIOD,
        A.TRANS_CURRENT,
        A.TRANS_MODULE,
        A.NFAKTUR,
        A.DESCRIPTION,
        A.NSHARE,
        A.BRANCH,
        A.CURRENCY,
        A.AMOUNT,
        A.AMOUNTIDR,
        A.GEN_DATE,
        CASE WHEN M.CODE IS NOT NULL THEN 'KIK' ELSE 'NONKIK' END AS TYPE
    FROM DENPASAR.LEDGER_HISTORICAL@cammon A
    LEFT JOIN MF_CLIENTS M ON M.CODE = A.SUBACCOUNT
    WHERE A.ACCOUNT       = '10401021'
      AND A.TRANS_DUEDATE BETWEEN DENPASAR.CALCULATE_DUEDATE(TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyy-mm-dd'), 1)
                              AND DENPASAR.CALCULATE_DUEDATE(TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyy-mm-dd'), 2)
      AND A.TRANS_MODULE  = 20
      AND A.TRANS_PERIOD  = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyymm')
      AND A.SUBACCOUNT    LIKE '17%'
      AND A.GEN_DATE      = TO_DATE('2026-04-21','yyyy-mm-dd')
),
BASE_WITH_GROUP_NET AS (
    SELECT
        BR.*,
        SUM(BR.AMOUNT) OVER (PARTITION BY BR.SUBACCOUNT, BR.TRANS_DUEDATE) AS GROUP_NET_AMOUNT
    FROM BASE_ROWS BR
)
SELECT
    TYPE,
    ACCOUNT,
    SUBACCOUNT,
    TRANS_DATE,
    TRANS_DUEDATE,
    TRANS_PERIOD,
    TRANS_CURRENT,
    TRANS_MODULE,
    NFAKTUR,
    DESCRIPTION,
    NSHARE,
    BRANCH,
    CASE
        WHEN TYPE = 'KIK'    AND AMOUNT > 0           THEN AMOUNT
        WHEN TYPE = 'NONKIK' AND GROUP_NET_AMOUNT > 0 THEN AMOUNT
    END AS NET_AMOUNT
FROM BASE_WITH_GROUP_NET
WHERE (TYPE = 'KIK'    AND AMOUNT > 0)
   OR (TYPE = 'NONKIK' AND GROUP_NET_AMOUNT > 0)
ORDER BY TYPE, SUBACCOUNT, TRANS_DUEDATE, TRANS_DATE, NFAKTUR;