SELECT ID, NSHARE_NAME, RATING, PRICE, QUANTITY, MARKET_VALUE, HAIRCUT_VALUE, CONCERN_RISK, AFFILIATED, GROUPSHARE, ACQUISITION_PRICE, SUKUK
                        FROM MKBD.MKBD_EBUS
                        WHERE RECDATE = TO_DATE('2026-04-08', 'yyyy-mm-dd')