SELECT TRANS_PERIOD, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUE, TRANS_CURRENT, TRANS_BOARD, ACCOUNT, NCLIENT, NSHARE, CURRENCY, QUANTITY, PRICE, AMOUNT
                              FROM MKBD.MKBD_COMPILED_TRADES TL
                              --WHERE TL.GEN_DATE = TO_DATE('2026-04-21', 'YYYY-MM-DD')
                                WHERE ACCOUNT = '103'