SELECT TL.TRANS_FLAG,
       TL.TRANS_MODULE,
       TL.TRANS_NO,
       TL.TRANS_DATE,
       TL.TRANS_DUEDATE,
       TL.NSHARE,
       TL.ACCOUNT,
       TL.SUBACCOUNT,
       TL.DESCRIPTION,
       TL.CURRENCY,
       TL.AMOUNT,
       TL.EXCHANGERATE,
       TL.AMOUNTIDR
FROM MKBD.MKBD_FINAL_JOURNAL TL,
     DENPASAR.ACCOUNT A
WHERE TL.GEN_DATE = TO_DATE('2026-04-21', 'YYYY-MM-DD')
  AND A.CODE = TL.ACCOUNT
  AND SOURCE_ID IN ('702', '703', '704', '705', '706')