WITH
-- ============================================================
-- AGING CTEs untuk account 10401021
-- ============================================================
DEBITS_10401021 AS (
    SELECT MAX(ID) AS ID, TRANS_MODULE, MAX(TRANS_NO) AS TRANS_NO,
           TRANS_DATE, TRANS_DUEDATE, ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT,
           BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           SUM(AMOUNT) AS DEBIT, SUM(AMOUNTIDR) AS DEBITIDR,
           CAST(NULL AS VARCHAR2(255)) AS DESCRIPTION
    FROM DENPASAR.LEDGER_HISTORICAL@CAMMON
    WHERE ACCOUNT = '10401021' AND SUBACCOUNT_TYPE = 1
      AND TRANS_MODULE IN (20, 21, 22)
      AND TRANS_PERIOD  = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'YYYYMM')
      AND TRANS_DUEDATE <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND GEN_DATE      = TO_DATE('2026-04-21','yyyy-mm-dd')
    GROUP BY TRANS_MODULE, TRANS_DATE, TRANS_DUEDATE, ACCOUNT, SUBACCOUNT_TYPE,
             SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE
    HAVING SUM(AMOUNT) > 0
    UNION ALL
    SELECT ID, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUEDATE,
           ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           AMOUNT AS DEBIT, AMOUNTIDR AS DEBITIDR, DESCRIPTION
    FROM DENPASAR.LEDGER_HISTORICAL@CAMMON
    WHERE ACCOUNT = '10401021' AND SUBACCOUNT_TYPE = 1
      AND TRANS_MODULE NOT IN (20, 21, 22)
      AND TRANS_PERIOD = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'YYYYMM')
      AND TRANS_DATE  <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND GEN_DATE     = TO_DATE('2026-04-21','yyyy-mm-dd')
      AND AMOUNT > 0
),
CREDITS_10401021 AS (
    SELECT ID, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUEDATE,
           ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           -AMOUNT AS CREDIT, -AMOUNTIDR AS CREDITIDR, DESCRIPTION
    FROM DENPASAR.LEDGER_HISTORICAL@CAMMON
    WHERE ACCOUNT = '10401021' AND SUBACCOUNT_TYPE = 1
      AND TRANS_MODULE NOT IN (20, 21, 22)
      AND TRANS_PERIOD = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'YYYYMM')
      AND TRANS_DATE  <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND GEN_DATE     = TO_DATE('2026-04-21','yyyy-mm-dd')
      AND AMOUNT < 0
    UNION ALL
    SELECT MAX(ID) AS ID, TRANS_MODULE, MAX(TRANS_NO) AS TRANS_NO,
           TRANS_DATE, TRANS_DUEDATE, ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT,
           BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           -SUM(AMOUNT) AS CREDIT, -SUM(AMOUNTIDR) AS CREDITIDR,
           CAST(NULL AS VARCHAR2(255)) AS DESCRIPTION
    FROM DENPASAR.LEDGER_HISTORICAL@CAMMON
    WHERE ACCOUNT = '10401021' AND SUBACCOUNT_TYPE = 1
      AND TRANS_MODULE IN (20, 21, 22)
      AND TRANS_PERIOD  = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'YYYYMM')
      AND TRANS_DUEDATE <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND GEN_DATE      = TO_DATE('2026-04-21','yyyy-mm-dd')
    GROUP BY TRANS_MODULE, TRANS_DATE, TRANS_DUEDATE, ACCOUNT, SUBACCOUNT_TYPE,
             SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE
    HAVING SUM(AMOUNT) < 0
),
CREDIT_TOTALS_10401021 AS (
    SELECT ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY,
           SUM(CREDIT) AS TOTAL_CREDIT, SUM(CREDITIDR) AS TOTAL_CREDITIDR
    FROM CREDITS_10401021
    GROUP BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
),
DEBIT_TOTALS_10401021 AS (
    SELECT ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY,
           SUM(DEBIT) AS TOTAL_DEBIT, SUM(DEBITIDR) AS TOTAL_DEBITIDR
    FROM DEBITS_10401021
    GROUP BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
),
DEBITS_NUMBERED_10401021 AS (
    SELECT D.*,
           NVL(SUM(DEBIT) OVER (
                   PARTITION BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
                   ORDER BY TRANS_DUEDATE, TRANS_DATE, ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING), 0) AS CUM_DEBIT_BEFORE,
           SUM(DEBIT) OVER (
                   PARTITION BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
                   ORDER BY TRANS_DUEDATE, TRANS_DATE, ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUM_DEBIT_AFTER
    FROM DEBITS_10401021 D
),
MATCHED_DEBITS_10401021 AS (
    SELECT D.ID, D.TRANS_MODULE, D.TRANS_NO, D.TRANS_DATE, D.TRANS_DUEDATE,
           D.ACCOUNT, D.SUBACCOUNT_TYPE, D.SUBACCOUNT, D.BRANCH, D.NFAKTUR,
           D.CURRENCY, D.EXCHANGERATE, D.DESCRIPTION,
           D.DEBIT AS ORIGINAL_DEBIT, D.DEBITIDR AS ORIGINAL_DEBITIDR,
           CASE
               WHEN NVL(CT.TOTAL_CREDIT, 0) <= D.CUM_DEBIT_BEFORE THEN D.DEBIT
               WHEN NVL(CT.TOTAL_CREDIT, 0) >= D.CUM_DEBIT_AFTER  THEN 0
               ELSE D.CUM_DEBIT_AFTER - CT.TOTAL_CREDIT
           END AS REMAINING_DEBIT,
           CASE
               WHEN NVL(CT.TOTAL_CREDIT, 0) <= D.CUM_DEBIT_BEFORE THEN D.DEBITIDR
               WHEN NVL(CT.TOTAL_CREDIT, 0) >= D.CUM_DEBIT_AFTER  THEN 0
               ELSE CASE WHEN D.DEBIT = 0 THEN 0
                         ELSE D.DEBITIDR * ((D.CUM_DEBIT_AFTER - CT.TOTAL_CREDIT) / D.DEBIT) END
           END AS REMAINING_DEBITIDR
    FROM DEBITS_NUMBERED_10401021 D
    LEFT JOIN CREDIT_TOTALS_10401021 CT
           ON D.ACCOUNT         = CT.ACCOUNT
          AND D.SUBACCOUNT_TYPE = CT.SUBACCOUNT_TYPE
          AND D.SUBACCOUNT      = CT.SUBACCOUNT
          AND D.BRANCH          = CT.BRANCH
          AND D.CURRENCY        = CT.CURRENCY
),
CREDITS_NUMBERED_10401021 AS (
    SELECT C.*,
           NVL(SUM(CREDIT) OVER (
                   PARTITION BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
                   ORDER BY NFAKTUR, TRANS_DUEDATE, TRANS_DATE, ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING), 0) AS CUM_CREDIT_BEFORE,
           SUM(CREDIT) OVER (
                   PARTITION BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
                   ORDER BY NFAKTUR, TRANS_DUEDATE, TRANS_DATE, ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUM_CREDIT_AFTER
    FROM CREDITS_10401021 C
),
UNMATCHED_CREDITS_10401021 AS (
    SELECT C.ID, C.TRANS_MODULE, C.TRANS_NO, C.TRANS_DATE, C.TRANS_DUEDATE,
           C.ACCOUNT, C.SUBACCOUNT_TYPE, C.SUBACCOUNT, C.BRANCH, C.NFAKTUR,
           C.CURRENCY, C.EXCHANGERATE, C.DESCRIPTION,
           CASE
               WHEN NVL(DT.TOTAL_DEBIT, 0) >= C.CUM_CREDIT_AFTER  THEN 0
               WHEN NVL(DT.TOTAL_DEBIT, 0) <= C.CUM_CREDIT_BEFORE THEN -C.CREDIT
               ELSE -(C.CUM_CREDIT_AFTER - DT.TOTAL_DEBIT)
           END AS UNMATCHED_DEBIT,
           CASE
               WHEN NVL(DT.TOTAL_DEBIT, 0) >= C.CUM_CREDIT_AFTER  THEN 0
               WHEN NVL(DT.TOTAL_DEBIT, 0) <= C.CUM_CREDIT_BEFORE THEN -C.CREDITIDR
               ELSE CASE WHEN C.CREDIT = 0 THEN 0
                         ELSE -C.CREDITIDR * ((C.CUM_CREDIT_AFTER - DT.TOTAL_DEBIT) / C.CREDIT) END
           END AS UNMATCHED_DEBITIDR
    FROM CREDITS_NUMBERED_10401021 C
    LEFT JOIN DEBIT_TOTALS_10401021 DT
           ON C.ACCOUNT         = DT.ACCOUNT
          AND C.SUBACCOUNT_TYPE = DT.SUBACCOUNT_TYPE
          AND C.SUBACCOUNT      = DT.SUBACCOUNT
          AND C.BRANCH          = DT.BRANCH
          AND C.CURRENCY        = DT.CURRENCY
),
AGING_10401021 AS (
    SELECT ID, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUEDATE,
           ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           REMAINING_DEBIT AS DEBIT, REMAINING_DEBITIDR AS DEBITIDR, DESCRIPTION,
           CASE WHEN REMAINING_DEBIT < 0 THEN 1 ELSE 0 END AS PL
    FROM MATCHED_DEBITS_10401021
    WHERE REMAINING_DEBIT <> 0
    UNION ALL
    SELECT ID, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUEDATE,
           ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           UNMATCHED_DEBIT AS DEBIT, UNMATCHED_DEBITIDR AS DEBITIDR, DESCRIPTION, 1 AS PL
    FROM UNMATCHED_CREDITS_10401021
    WHERE UNMATCHED_DEBIT <> 0
),
-- ============================================================
-- AGING CTEs untuk account 10401031 (strukturnya identik)
-- ============================================================
DEBITS_10401031 AS (
    SELECT MAX(ID) AS ID, TRANS_MODULE, MAX(TRANS_NO) AS TRANS_NO,
           TRANS_DATE, TRANS_DUEDATE, ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT,
           BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           SUM(AMOUNT) AS DEBIT, SUM(AMOUNTIDR) AS DEBITIDR,
           CAST(NULL AS VARCHAR2(255)) AS DESCRIPTION
    FROM DENPASAR.LEDGER_HISTORICAL@CAMMON
    WHERE ACCOUNT = '10401031' AND SUBACCOUNT_TYPE = 1
      AND TRANS_MODULE IN (20, 21, 22)
      AND TRANS_PERIOD  = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'YYYYMM')
      AND TRANS_DUEDATE <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND GEN_DATE      = TO_DATE('2026-04-21','yyyy-mm-dd')
    GROUP BY TRANS_MODULE, TRANS_DATE, TRANS_DUEDATE, ACCOUNT, SUBACCOUNT_TYPE,
             SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE
    HAVING SUM(AMOUNT) > 0
    UNION ALL
    SELECT ID, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUEDATE,
           ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           AMOUNT AS DEBIT, AMOUNTIDR AS DEBITIDR, DESCRIPTION
    FROM DENPASAR.LEDGER_HISTORICAL@CAMMON
    WHERE ACCOUNT = '10401031' AND SUBACCOUNT_TYPE = 1
      AND TRANS_MODULE NOT IN (20, 21, 22)
      AND TRANS_PERIOD = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'YYYYMM')
      AND TRANS_DATE  <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND GEN_DATE     = TO_DATE('2026-04-21','yyyy-mm-dd')
      AND AMOUNT > 0
),
CREDITS_10401031 AS (
    SELECT ID, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUEDATE,
           ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           -AMOUNT AS CREDIT, -AMOUNTIDR AS CREDITIDR, DESCRIPTION
    FROM DENPASAR.LEDGER_HISTORICAL@CAMMON
    WHERE ACCOUNT = '10401031' AND SUBACCOUNT_TYPE = 1
      AND TRANS_MODULE NOT IN (20, 21, 22)
      AND TRANS_PERIOD = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'YYYYMM')
      AND TRANS_DATE  <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND GEN_DATE     = TO_DATE('2026-04-21','yyyy-mm-dd')
      AND AMOUNT < 0
    UNION ALL
    SELECT MAX(ID) AS ID, TRANS_MODULE, MAX(TRANS_NO) AS TRANS_NO,
           TRANS_DATE, TRANS_DUEDATE, ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT,
           BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           -SUM(AMOUNT) AS CREDIT, -SUM(AMOUNTIDR) AS CREDITIDR,
           CAST(NULL AS VARCHAR2(255)) AS DESCRIPTION
    FROM DENPASAR.LEDGER_HISTORICAL@CAMMON
    WHERE ACCOUNT = '10401031' AND SUBACCOUNT_TYPE = 1
      AND TRANS_MODULE IN (20, 21, 22)
      AND TRANS_PERIOD  = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'YYYYMM')
      AND TRANS_DUEDATE <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND GEN_DATE      = TO_DATE('2026-04-21','yyyy-mm-dd')
    GROUP BY TRANS_MODULE, TRANS_DATE, TRANS_DUEDATE, ACCOUNT, SUBACCOUNT_TYPE,
             SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE
    HAVING SUM(AMOUNT) < 0
),
CREDIT_TOTALS_10401031 AS (
    SELECT ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY,
           SUM(CREDIT) AS TOTAL_CREDIT, SUM(CREDITIDR) AS TOTAL_CREDITIDR
    FROM CREDITS_10401031
    GROUP BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
),
DEBIT_TOTALS_10401031 AS (
    SELECT ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY,
           SUM(DEBIT) AS TOTAL_DEBIT, SUM(DEBITIDR) AS TOTAL_DEBITIDR
    FROM DEBITS_10401031
    GROUP BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
),
DEBITS_NUMBERED_10401031 AS (
    SELECT D.*,
           NVL(SUM(DEBIT) OVER (
                   PARTITION BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
                   ORDER BY TRANS_DUEDATE, TRANS_DATE, ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING), 0) AS CUM_DEBIT_BEFORE,
           SUM(DEBIT) OVER (
                   PARTITION BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
                   ORDER BY TRANS_DUEDATE, TRANS_DATE, ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUM_DEBIT_AFTER
    FROM DEBITS_10401031 D
),
MATCHED_DEBITS_10401031 AS (
    SELECT D.ID, D.TRANS_MODULE, D.TRANS_NO, D.TRANS_DATE, D.TRANS_DUEDATE,
           D.ACCOUNT, D.SUBACCOUNT_TYPE, D.SUBACCOUNT, D.BRANCH, D.NFAKTUR,
           D.CURRENCY, D.EXCHANGERATE, D.DESCRIPTION,
           D.DEBIT AS ORIGINAL_DEBIT, D.DEBITIDR AS ORIGINAL_DEBITIDR,
           CASE
               WHEN NVL(CT.TOTAL_CREDIT, 0) <= D.CUM_DEBIT_BEFORE THEN D.DEBIT
               WHEN NVL(CT.TOTAL_CREDIT, 0) >= D.CUM_DEBIT_AFTER  THEN 0
               ELSE D.CUM_DEBIT_AFTER - CT.TOTAL_CREDIT
           END AS REMAINING_DEBIT,
           CASE
               WHEN NVL(CT.TOTAL_CREDIT, 0) <= D.CUM_DEBIT_BEFORE THEN D.DEBITIDR
               WHEN NVL(CT.TOTAL_CREDIT, 0) >= D.CUM_DEBIT_AFTER  THEN 0
               ELSE CASE WHEN D.DEBIT = 0 THEN 0
                         ELSE D.DEBITIDR * ((D.CUM_DEBIT_AFTER - CT.TOTAL_CREDIT) / D.DEBIT) END
           END AS REMAINING_DEBITIDR
    FROM DEBITS_NUMBERED_10401031 D
    LEFT JOIN CREDIT_TOTALS_10401031 CT
           ON D.ACCOUNT         = CT.ACCOUNT
          AND D.SUBACCOUNT_TYPE = CT.SUBACCOUNT_TYPE
          AND D.SUBACCOUNT      = CT.SUBACCOUNT
          AND D.BRANCH          = CT.BRANCH
          AND D.CURRENCY        = CT.CURRENCY
),
CREDITS_NUMBERED_10401031 AS (
    SELECT C.*,
           NVL(SUM(CREDIT) OVER (
                   PARTITION BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
                   ORDER BY NFAKTUR, TRANS_DUEDATE, TRANS_DATE, ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING), 0) AS CUM_CREDIT_BEFORE,
           SUM(CREDIT) OVER (
                   PARTITION BY ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, CURRENCY
                   ORDER BY NFAKTUR, TRANS_DUEDATE, TRANS_DATE, ID
                   ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS CUM_CREDIT_AFTER
    FROM CREDITS_10401031 C
),
UNMATCHED_CREDITS_10401031 AS (
    SELECT C.ID, C.TRANS_MODULE, C.TRANS_NO, C.TRANS_DATE, C.TRANS_DUEDATE,
           C.ACCOUNT, C.SUBACCOUNT_TYPE, C.SUBACCOUNT, C.BRANCH, C.NFAKTUR,
           C.CURRENCY, C.EXCHANGERATE, C.DESCRIPTION,
           CASE
               WHEN NVL(DT.TOTAL_DEBIT, 0) >= C.CUM_CREDIT_AFTER  THEN 0
               WHEN NVL(DT.TOTAL_DEBIT, 0) <= C.CUM_CREDIT_BEFORE THEN -C.CREDIT
               ELSE -(C.CUM_CREDIT_AFTER - DT.TOTAL_DEBIT)
           END AS UNMATCHED_DEBIT,
           CASE
               WHEN NVL(DT.TOTAL_DEBIT, 0) >= C.CUM_CREDIT_AFTER  THEN 0
               WHEN NVL(DT.TOTAL_DEBIT, 0) <= C.CUM_CREDIT_BEFORE THEN -C.CREDITIDR
               ELSE CASE WHEN C.CREDIT = 0 THEN 0
                         ELSE -C.CREDITIDR * ((C.CUM_CREDIT_AFTER - DT.TOTAL_DEBIT) / C.CREDIT) END
           END AS UNMATCHED_DEBITIDR
    FROM CREDITS_NUMBERED_10401031 C
    LEFT JOIN DEBIT_TOTALS_10401031 DT
           ON C.ACCOUNT         = DT.ACCOUNT
          AND C.SUBACCOUNT_TYPE = DT.SUBACCOUNT_TYPE
          AND C.SUBACCOUNT      = DT.SUBACCOUNT
          AND C.BRANCH          = DT.BRANCH
          AND C.CURRENCY        = DT.CURRENCY
),
AGING_10401031 AS (
    SELECT ID, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUEDATE,
           ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           REMAINING_DEBIT AS DEBIT, REMAINING_DEBITIDR AS DEBITIDR, DESCRIPTION,
           CASE WHEN REMAINING_DEBIT < 0 THEN 1 ELSE 0 END AS PL
    FROM MATCHED_DEBITS_10401031
    WHERE REMAINING_DEBIT <> 0
    UNION ALL
    SELECT ID, TRANS_MODULE, TRANS_NO, TRANS_DATE, TRANS_DUEDATE,
           ACCOUNT, SUBACCOUNT_TYPE, SUBACCOUNT, BRANCH, NFAKTUR, CURRENCY, EXCHANGERATE,
           UNMATCHED_DEBIT AS DEBIT, UNMATCHED_DEBITIDR AS DEBITIDR, DESCRIPTION, 1 AS PL
    FROM UNMATCHED_CREDITS_10401031
    WHERE UNMATCHED_DEBIT <> 0
),
AGING_RECEIVABLE AS (
    SELECT * FROM AGING_10401021
    UNION ALL
    SELECT * FROM AGING_10401031
),
-- ============================================================
-- Klasifikasi aging rows ke HUTANG / DENDA / CUSTODY
-- Plus filter HAVING SUM per (SUBACCOUNT, COMPONENT) > 0
-- ============================================================
AGING_CLASSIFIED AS (
    SELECT
        AR.*,
        CASE
            WHEN AR.DEBIT <> 0 AND AR.TRANS_MODULE = 12
                 THEN 'DENDA'
            WHEN AR.DEBIT <> 0 AND AR.TRANS_MODULE IN (13, 15)
                 AND (AR.DESCRIPTION LIKE '%CUSTODY%'
                   OR AR.DESCRIPTION LIKE '%KUSTODI%'
                   OR AR.DESCRIPTION LIKE '%METERAI%'
                   OR AR.DESCRIPTION LIKE '%MARKET DATA%')
                 THEN 'CUSTODY'
            WHEN AR.DEBIT <> 0
                 AND (AR.TRANS_MODULE NOT IN (12, 13, 15)
                   OR (AR.TRANS_MODULE IN (13, 15) AND AR.DESCRIPTION LIKE '%DEVIDEN%')
                   OR (AR.TRANS_MODULE IN (13, 15) AND AR.DESCRIPTION LIKE '%W/O%')
                   OR (AR.TRANS_MODULE IN (13, 15) AND AR.DESCRIPTION LIKE '%IPO'))
                 THEN 'HUTANG'
            ELSE 'UNCLASSIFIED'
        END AS COMPONENT
    FROM AGING_RECEIVABLE AR
    WHERE AR.DEBIT <> 0
),
AGING_WITH_CLIENT_TOTAL AS (
    SELECT
        AC.*,
        SUM(AC.DEBITIDR) OVER (PARTITION BY AC.SUBACCOUNT, AC.COMPONENT) AS CLIENT_COMPONENT_TOTAL
    FROM AGING_CLASSIFIED AC
),
-- ============================================================
-- GL detail: ledger rows yang masuk ke subaccount dengan nett > 0
-- ============================================================
GL_BASE AS (
    SELECT L.ACCOUNT, L.SUBACCOUNT, L.AMOUNTIDR, L.AMOUNT,
           L.TRANS_DATE, L.TRANS_DUEDATE, L.TRANS_CURRENT, L.TRANS_MODULE,
           L.NFAKTUR, L.DESCRIPTION, L.NSHARE, L.BRANCH, L.CURRENCY
    FROM DENPASAR.LEDGER_HISTORICAL@cammon L
    INNER JOIN DENPASAR.ACCOUNT A ON L.ACCOUNT = A.CODE
    WHERE L.TRANS_PERIOD   = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyymm')
      AND L.TRANS_CURRENT  = 0
      AND A.SUBACCOUNT_TYPE > 0
      AND L.TRANS_DUEDATE <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND L.ACCOUNT IN ('10401021','10401022','10401031','10401071')
      AND L.GEN_DATE       = TO_DATE('2026-04-21','yyyy-mm-dd')
    UNION ALL
    SELECT L.ACCOUNT, L.SUBACCOUNT, L.AMOUNTIDR, L.AMOUNT,
           L.TRANS_DATE, L.TRANS_DUEDATE, L.TRANS_CURRENT, L.TRANS_MODULE,
           L.NFAKTUR, L.DESCRIPTION, L.NSHARE, L.BRANCH, L.CURRENCY
    FROM DENPASAR.LEDGER_HISTORICAL@cammon L
    INNER JOIN DENPASAR.ACCOUNT A ON L.ACCOUNT = A.CODE
    WHERE L.ACCOUNT IN ('10401021','10401022','10401031','10401071')
      AND L.TRANS_DATE    >= TRUNC(TO_DATE('2026-04-21','yyyy-mm-dd'),'MM')
      AND L.TRANS_DUEDATE <= TO_DATE('2026-04-21','yyyy-mm-dd')
      AND L.TRANS_CURRENT  = 1
      AND A.SUBACCOUNT_TYPE > 0
      AND L.GEN_DATE       = TO_DATE('2026-04-21','yyyy-mm-dd')
),
GL_WITH_SUBACCT_NET AS (
    SELECT GB.*,
           SUM(GB.AMOUNTIDR) OVER (PARTITION BY GB.ACCOUNT, GB.SUBACCOUNT) AS SUBACCT_NET
    FROM GL_BASE GB
),
-- ============================================================
-- Totals untuk validasi summary
-- ============================================================
COMPONENT_TOTALS AS (
    SELECT
        SUM(CASE WHEN COMPONENT = 'HUTANG'  AND CLIENT_COMPONENT_TOTAL > 0 THEN DEBITIDR ELSE 0 END) AS OUTSTANDING_AMOUNT,
        SUM(CASE WHEN COMPONENT = 'DENDA'   AND CLIENT_COMPONENT_TOTAL > 0 THEN DEBITIDR ELSE 0 END) AS INTEREST_AMOUNT,
        SUM(CASE WHEN COMPONENT = 'CUSTODY' AND CLIENT_COMPONENT_TOTAL > 0 THEN DEBITIDR ELSE 0 END) AS CUSTODY_AMOUNT
    FROM AGING_WITH_CLIENT_TOTAL
),
GL_TOTAL AS (
    SELECT NVL(SUM(AMOUNTIDR), 0) AS GL_SUM
    FROM GL_WITH_SUBACCT_NET
    WHERE SUBACCT_NET > 0
)
-- ============================================================
-- UNION ALL: detail breakdown + summary
-- ============================================================
SELECT
    SECTION,
    SORT_KEY,
    COMPONENT,
    CLIENT_CODE,
    CLIENT_NAME,
    ACCOUNT,
    SUBACCOUNT,
    TRANS_MODULE,
    TRANS_DATE,
    TRANS_DUEDATE,
    NFAKTUR,
    DESCRIPTION,
    BRANCH,
    CURRENCY,
    DEBITIDR,
    AMOUNTIDR,
    SUBACCT_NET,
    CLIENT_COMPONENT_TOTAL,
    OUTSTANDING_AMOUNT,
    INTEREST_AMOUNT,
    CUSTODY_AMOUNT,
    GL_SUM,
    TOTAL_RESULT
FROM (
    -- === Section 1: HUTANG / DENDA / CUSTODY detail (per client, per aging row) ===
    SELECT
        '1_AGING_DETAIL'          AS SECTION,
        1                         AS SORT_KEY,
        AWT.COMPONENT             AS COMPONENT,
        C.CODE                    AS CLIENT_CODE,
        C.NAME                    AS CLIENT_NAME,
        AWT.ACCOUNT               AS ACCOUNT,
        AWT.SUBACCOUNT            AS SUBACCOUNT,
        AWT.TRANS_MODULE          AS TRANS_MODULE,
        AWT.TRANS_DATE            AS TRANS_DATE,
        AWT.TRANS_DUEDATE         AS TRANS_DUEDATE,
        AWT.NFAKTUR               AS NFAKTUR,
        AWT.DESCRIPTION           AS DESCRIPTION,
        AWT.BRANCH                AS BRANCH,
        AWT.CURRENCY              AS CURRENCY,
        AWT.DEBITIDR              AS DEBITIDR,
        CAST(NULL AS NUMBER)      AS AMOUNTIDR,
        CAST(NULL AS NUMBER)      AS SUBACCT_NET,
        AWT.CLIENT_COMPONENT_TOTAL AS CLIENT_COMPONENT_TOTAL,
        CAST(NULL AS NUMBER)      AS OUTSTANDING_AMOUNT,
        CAST(NULL AS NUMBER)      AS INTEREST_AMOUNT,
        CAST(NULL AS NUMBER)      AS CUSTODY_AMOUNT,
        CAST(NULL AS NUMBER)      AS GL_SUM,
        CAST(NULL AS NUMBER)      AS TOTAL_RESULT
    FROM AGING_WITH_CLIENT_TOTAL AWT
    INNER JOIN DENPASAR.CLIENT C ON AWT.SUBACCOUNT = C.CODE
    WHERE AWT.COMPONENT IN ('HUTANG','DENDA','CUSTODY')
      AND AWT.CLIENT_COMPONENT_TOTAL > 0

    UNION ALL

    -- === Section 2: GL_SUM detail (per ledger row, hanya subaccount nett > 0) ===
    SELECT
        '2_GL_DETAIL'         AS SECTION,
        2                     AS SORT_KEY,
        'GL'                  AS COMPONENT,
        CAST(NULL AS VARCHAR2(20)) AS CLIENT_CODE,
        CAST(NULL AS VARCHAR2(100)) AS CLIENT_NAME,
        GWS.ACCOUNT           AS ACCOUNT,
        GWS.SUBACCOUNT        AS SUBACCOUNT,
        GWS.TRANS_MODULE      AS TRANS_MODULE,
        GWS.TRANS_DATE        AS TRANS_DATE,
        GWS.TRANS_DUEDATE     AS TRANS_DUEDATE,
        GWS.NFAKTUR           AS NFAKTUR,
        GWS.DESCRIPTION       AS DESCRIPTION,
        GWS.BRANCH            AS BRANCH,
        GWS.CURRENCY          AS CURRENCY,
        CAST(NULL AS NUMBER)  AS DEBITIDR,
        GWS.AMOUNTIDR         AS AMOUNTIDR,
        GWS.SUBACCT_NET       AS SUBACCT_NET,
        CAST(NULL AS NUMBER)  AS CLIENT_COMPONENT_TOTAL,
        CAST(NULL AS NUMBER)  AS OUTSTANDING_AMOUNT,
        CAST(NULL AS NUMBER)  AS INTEREST_AMOUNT,
        CAST(NULL AS NUMBER)  AS CUSTODY_AMOUNT,
        CAST(NULL AS NUMBER)  AS GL_SUM,
        CAST(NULL AS NUMBER)  AS TOTAL_RESULT
    FROM GL_WITH_SUBACCT_NET GWS
    WHERE GWS.SUBACCT_NET > 0

    UNION ALL

    -- === Section 3: SUMMARY (totals + final result) ===
    SELECT
        '3_SUMMARY'              AS SECTION,
        3                        AS SORT_KEY,
        'SUMMARY'                AS COMPONENT,
        CAST(NULL AS VARCHAR2(20)) AS CLIENT_CODE,
        CAST(NULL AS VARCHAR2(100)) AS CLIENT_NAME,
        CAST(NULL AS VARCHAR2(20)) AS ACCOUNT,
        CAST(NULL AS VARCHAR2(20)) AS SUBACCOUNT,
        CAST(NULL AS NUMBER)     AS TRANS_MODULE,
        CAST(NULL AS DATE)       AS TRANS_DATE,
        CAST(NULL AS DATE)       AS TRANS_DUEDATE,
        CAST(NULL AS VARCHAR2(20)) AS NFAKTUR,
        CAST(NULL AS VARCHAR2(255)) AS DESCRIPTION,
        CAST(NULL AS VARCHAR2(20)) AS BRANCH,
        CAST(NULL AS VARCHAR2(3))  AS CURRENCY,
        CAST(NULL AS NUMBER)     AS DEBITIDR,
        CAST(NULL AS NUMBER)     AS AMOUNTIDR,
        CAST(NULL AS NUMBER)     AS SUBACCT_NET,
        CAST(NULL AS NUMBER)     AS CLIENT_COMPONENT_TOTAL,
        CT.OUTSTANDING_AMOUNT    AS OUTSTANDING_AMOUNT,
        CT.INTEREST_AMOUNT       AS INTEREST_AMOUNT,
        CT.CUSTODY_AMOUNT        AS CUSTODY_AMOUNT,
        GT.GL_SUM                AS GL_SUM,
        (CT.INTEREST_AMOUNT + CT.CUSTODY_AMOUNT
           + (GT.GL_SUM - (CT.OUTSTANDING_AMOUNT + CT.INTEREST_AMOUNT + CT.CUSTODY_AMOUNT)))
                                 AS TOTAL_RESULT
    FROM COMPONENT_TOTALS CT
    CROSS JOIN GL_TOTAL GT
)
ORDER BY SORT_KEY, COMPONENT, CLIENT_CODE, ACCOUNT, SUBACCOUNT, TRANS_DATE;