WITH
ledger_net_per_acc_sub AS (
    SELECT ACCOUNT, SUBACCOUNT, SUM(AMOUNTIDR) AS NET_AMOUNTIDR
    FROM (
        -- Opening balance (TRANS_CURRENT = 0)
        SELECT L.ACCOUNT, L.SUBACCOUNT, SUM(L.AMOUNTIDR) AS AMOUNTIDR
        FROM DENPASAR.LEDGER_HISTORICAL@cammon L
        INNER JOIN DENPASAR.ACCOUNT A ON L.ACCOUNT = A.CODE
        WHERE L.TRANS_PERIOD    = TO_CHAR(TO_DATE('2026-05-19','yyyy-mm-dd'),'yyyymm')
          AND L.TRANS_CURRENT   = 0
          AND A.SUBACCOUNT_TYPE > 0
          AND L.ACCOUNT IN ('10401021','10401022','10401031','10401071','10401131')
          AND L.TRANS_DUEDATE  <= TO_DATE('2026-05-19','yyyy-mm-dd')
          AND L.GEN_DATE        = TO_DATE('2026-05-19','yyyy-mm-dd')
        GROUP BY L.ACCOUNT, L.SUBACCOUNT
        UNION ALL
        -- Current month transactions (TRANS_CURRENT > 0)
        SELECT ACCOUNT, SUBACCOUNT, SUM(AMOUNTIDR)
        FROM DENPASAR.LEDGER_HISTORICAL@cammon
        WHERE ACCOUNT IN ('10401021','10401022','10401031','10401071','10401131')
          AND TRANS_DATE    >= TRUNC(TO_DATE('2026-05-19','yyyy-mm-dd'),'MM')
          AND TRANS_DUEDATE <= TO_DATE('2026-05-19','yyyy-mm-dd')
          AND TRANS_CURRENT  > 0
          AND GEN_DATE       = TO_DATE('2026-05-19','yyyy-mm-dd')
        GROUP BY ACCOUNT, SUBACCOUNT
    )
    GROUP BY ACCOUNT, SUBACCOUNT
    HAVING SUM(AMOUNTIDR) < 0
),
-- Step 3: Anti-join — hanya client TANPA interest agreement
ledger_non_ia AS (
    SELECT N.ACCOUNT, N.SUBACCOUNT, ABS(N.NET_AMOUNTIDR) AS AMOUNTIDR
    FROM ledger_net_per_acc_sub N
    LEFT JOIN DENPASAR.CLIENT_PROPERTY B
      ON N.SUBACCOUNT = B.CLIENT_ID AND B.INTEREST_AGRREMENT = 1
    WHERE B.CLIENT_ID IS NULL
),
-- MKBD detail
mkbd_part AS (
    SELECT
        ACCOUNT,
        ENDBAL_DEBIT,
        ENDBAL_CREDIT,
        CASE WHEN ENDBAL_DEBIT  < 0 THEN -ENDBAL_DEBIT  ELSE 0 END
      + CASE WHEN ENDBAL_CREDIT > 0 THEN  ENDBAL_CREDIT ELSE 0 END AS AMT
    FROM MKBD.MKBD_BALANCE_SUMMARY
    WHERE GEN_DATE        = TO_DATE('2026-05-19','yyyy-mm-dd')
      AND ACCOUNT         = '20689991'
      AND LENGTH(ACCOUNT) = 8
      AND MKBD_FLAG       = 0
)

SELECT LVL, SOURCE, ACCOUNT, SUBACCOUNT, AMT
FROM (

    SELECT 1 AS LVL,
           'LEDGER Non-IA detail' AS SOURCE,
           ACCOUNT, SUBACCOUNT, AMOUNTIDR AS AMT
    FROM ledger_non_ia
    UNION ALL

    SELECT 2, 'LEDGER Non-IA subtotal (per ACCOUNT)',
           ACCOUNT, NULL, SUM(AMOUNTIDR)
    FROM ledger_non_ia
    GROUP BY ACCOUNT
    UNION ALL

    SELECT 3, 'LEDGER Non-IA TOTAL',
           NULL, NULL, SUM(AMOUNTIDR)
    FROM ledger_non_ia
    UNION ALL

    SELECT 4, 'MKBD_BALANCE detail',
           ACCOUNT, NULL, AMT
    FROM mkbd_part
    UNION ALL

    SELECT 5, 'MKBD_BALANCE TOTAL',
           NULL, NULL, NVL(SUM(AMT), 0)
    FROM mkbd_part
    UNION ALL

    SELECT 6, 'GRAND TOTAL',
           NULL, NULL,
           (SELECT NVL(SUM(AMOUNTIDR), 0) FROM ledger_non_ia)
         + (SELECT NVL(SUM(AMT), 0)       FROM mkbd_part)
    FROM DUAL
)
ORDER BY LVL, ACCOUNT NULLS LAST, SUBACCOUNT NULLS LAST;
