SELECT S.GEN_DATE,
       S.ID,
       S.TRANS_FLAG,
       S.MKBD_FLAG,
       S.ACCOUNT,
       S.SUBACCOUNT_TYPE,
       S.SUBACCOUNT,
       S.BRANCH,
       S.CURRENCY,
       S.OPENBAL,
       S.DEBIT,
       S.CREDIT,
       S.ENDBAL,
       S.ENDBAL_DEBIT,
       S.ENDBAL_CREDIT,
       S.OPENBAL_DEBIT,
       S.OPENBAL_CREDIT,
       S.CREATED_BY,
       S.CREATED_ON,
       S.CREATED_USING,
       S.UPDATED_BY,
       S.UPDATED_ON,
       S.UPDATED_USING
FROM MKBD.MAP_BANK MB
INNER JOIN MKBD.MKBD_BALANCE_SUMMARY S ON S.ACCOUNT = MB.NCLIENT
INNER JOIN DENPASAR.ACCOUNT ACC        ON ACC.CODE = S.ACCOUNT
WHERE S.GEN_DATE         = TO_DATE('2026-04-21', 'yyyy-mm-dd')
  AND LENGTH(MB.NCLIENT)   = 8
  AND LENGTH(MB.BANK_NAME) = 3
  AND MB.ISCLIENT          = 'N'
  AND ACC.ACCOUNT_TYPE     = (SELECT ID FROM DENPASAR.ACCOUNT_TYPE WHERE NAME = 'BANK')

UNION ALL

SELECT GEN_DATE,
       ID,
       TRANS_FLAG,
       MKBD_FLAG,
       ACCOUNT,
       SUBACCOUNT_TYPE,
       SUBACCOUNT,
       BRANCH,
       CURRENCY,
       OPENBAL,
       DEBIT,
       CREDIT,
       ENDBAL,
       ENDBAL_DEBIT,
       ENDBAL_CREDIT,
       OPENBAL_DEBIT,
       OPENBAL_CREDIT,
       CREATED_BY,
       CREATED_ON,
       CREATED_USING,
       UPDATED_BY,
       UPDATED_ON,
       UPDATED_USING
FROM MKBD.MKBD_BALANCE_SUMMARY
WHERE GEN_DATE        = TO_DATE('2026-04-21', 'yyyy-mm-dd')
  AND LENGTH(ACCOUNT)  = 8
  AND MKBD_FLAG        = 0
  AND ACCOUNT LIKE '10101%'

UNION ALL

SELECT TO_DATE('2026-04-21','yyyy-mm-dd') AS GEN_DATE,
       CAST(NULL AS NUMBER)               AS ID,
       CAST(NULL AS NUMBER)               AS TRANS_FLAG,
       CAST(NULL AS NUMBER)               AS MKBD_FLAG,
       '207 - FINAL BALANCE'              AS ACCOUNT,
       CAST(NULL AS NUMBER)               AS SUBACCOUNT_TYPE,
       CAST(NULL AS VARCHAR2(20))         AS SUBACCOUNT,
       CAST(NULL AS VARCHAR2(20))         AS BRANCH,
       CAST(NULL AS VARCHAR2(1))          AS CURRENCY,
       CAST(NULL AS NUMBER)               AS OPENBAL,
       CAST(NULL AS NUMBER)               AS DEBIT,
       CAST(NULL AS NUMBER)               AS CREDIT,
       CAST(NULL AS NUMBER)               AS ENDBAL,
       -SUM(ABS(AP.AMOUNT))               AS ENDBAL_DEBIT,
       CAST(NULL AS NUMBER)               AS ENDBAL_CREDIT,
       CAST(NULL AS NUMBER)               AS OPENBAL_DEBIT,
       CAST(NULL AS NUMBER)               AS OPENBAL_CREDIT,
       CAST(NULL AS VARCHAR2(12))         AS CREATED_BY,
       CAST(NULL AS DATE)                 AS CREATED_ON,
       CAST(NULL AS VARCHAR2(12))         AS CREATED_USING,
       CAST(NULL AS VARCHAR2(12))         AS UPDATED_BY,
       CAST(NULL AS DATE)                 AS UPDATED_ON,
       CAST(NULL AS VARCHAR2(12))         AS UPDATED_USING
FROM MKBD.MKBD_CLIENT_POSITION AP
INNER JOIN DENPASAR.CLIENT C           ON AP.NCLIENT = C.CODE
LEFT  JOIN DENPASAR.CLIENT_PROPERTY CP ON AP.NCLIENT = CP.CLIENT_ID
WHERE AP.TRANS_FLAG = 207
  AND AP.AMOUNT     < 0
  AND AP.GEN_DATE   = TO_DATE('2026-04-21', 'yyyy-mm-dd')
  AND (LENGTH(NVL(CP.BANK_ACC_NO_INVESTOR, '')) < 1 OR CP.BANK_ACC_NO_INVESTOR IS NULL)
  AND C.CLIENT_TYPE IN (12, 14, 16, 33)
