SELECT TRANS_FLAG,
       TRANS_MODULE,
       TRANS_NO,
       TRANS_DATE,
       TRANS_DUE,
       ACCOUNT,
       NCLIENT,
       NSHARE,
       QUANTITY,
       CURRENCY,
       PRICE,
       AMOUNT,
       EXCHANGERATE,
       AMOUNTIDR
FROM MKBD.MKBD_FINAL_TRADES TC
WHERE TC.GEN_DATE = TO_DATE('2026-04-21', 'YYYY-MM-DD')
  AND TC.SOURCE_ID IN ('644', '631')

