WITH DATE_NET AS (
    SELECT L.TRANS_DATE,
           SUM(CASE L.TRANS_FLAG
                   WHEN 911 THEN  L.AMOUNT
                   WHEN 912 THEN -L.AMOUNT
               END) AS MARKET_VALUE
    FROM MKBD.MKBD_COMPILED_JOURNAL L
    WHERE L.TRANS_FLAG IN (911, 912)
      AND L.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
      AND L.TRANS_DATE BETWEEN DENPASAR.CALCULATE_DUEDATE(:genDate, -2)
                           AND DENPASAR.CALCULATE_DUEDATE(:genDate,  0)
    GROUP BY L.TRANS_DATE
)
SELECT L.TRANS_FLAG,
       L.TRANS_MODULE,
       L.TRANS_NO,
       L.TRANS_DATE,
       L.TRANS_DUEDATE,
       L.ACCOUNT,
       NVL(A.NAME, NVL(L.ACCOUNT, '-')) AS ACCOUNT_NAME,
       L.SUBACCOUNT,
       NVL(C.NAME, NVL(L.SUBACCOUNT, '-')) AS CLIENT_NAME,
       L.DESCRIPTION,
       CASE L.TRANS_FLAG
           WHEN 911 THEN  L.AMOUNT
           WHEN 912 THEN -L.AMOUNT
       END AS SIGNED_AMOUNT
FROM MKBD.MKBD_COMPILED_JOURNAL L
JOIN DATE_NET D ON D.TRANS_DATE = L.TRANS_DATE
LEFT JOIN DENPASAR.ACCOUNT A ON L.ACCOUNT = A.CODE
LEFT JOIN DENPASAR.CLIENT C ON L.SUBACCOUNT = C.CODE
WHERE L.TRANS_FLAG IN (911, 912)
  AND L.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND L.TRANS_DATE BETWEEN DENPASAR.CALCULATE_DUEDATE(:genDate, -2)
                       AND DENPASAR.CALCULATE_DUEDATE(:genDate,  0)
  AND D.MARKET_VALUE < 0
ORDER BY L.TRANS_DATE, L.TRANS_FLAG