WITH MF_CLIENTS AS (
    SELECT CODE FROM DENPASAR.CLIENT WHERE SID LIKE 'MF%'
),
KIK AS (
    SELECT SUM(CASE WHEN AMOUNT < 0 THEN AMOUNT ELSE 0 END) AS VD52136
    FROM DENPASAR.LEDGER_HISTORICAL@cammon A
    WHERE A.ACCOUNT       = '10401021'
      AND A.TRANS_DUEDATE BETWEEN DENPASAR.CALCULATE_DUEDATE(TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyy-mm-dd'), 1)
                              AND DENPASAR.CALCULATE_DUEDATE(TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyy-mm-dd'), 2)
      AND A.TRANS_MODULE  = 20
      AND A.TRANS_PERIOD  = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyymm')
      AND A.SUBACCOUNT    LIKE '17%'
      AND A.GEN_DATE      = TO_DATE('2026-04-21','yyyy-mm-dd')
      AND EXISTS (SELECT 1 FROM MF_CLIENTS M WHERE M.CODE = A.SUBACCOUNT)
),
NONKIK AS (
    SELECT SUM(CASE WHEN NET_AMOUNT < 0 THEN NET_AMOUNT ELSE 0 END) AS VD52136
    FROM (
        SELECT
            A.SUBACCOUNT,
            A.TRANS_DUEDATE,
            SUM(AMOUNT) AS NET_AMOUNT
        FROM DENPASAR.LEDGER_HISTORICAL@cammon A
        WHERE A.ACCOUNT       = '10401021'
          AND A.TRANS_DUEDATE BETWEEN DENPASAR.CALCULATE_DUEDATE(TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyy-mm-dd'), 1)
                                  AND DENPASAR.CALCULATE_DUEDATE(TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyy-mm-dd'), 2)
          AND A.TRANS_MODULE  = 20
          AND A.TRANS_PERIOD  = TO_CHAR(TO_DATE('2026-04-21','yyyy-mm-dd'),'yyyymm')
          AND A.SUBACCOUNT    LIKE '17%'
          AND A.GEN_DATE      = TO_DATE('2026-04-21','yyyy-mm-dd')
          AND NOT EXISTS (SELECT 1 FROM MF_CLIENTS M WHERE M.CODE = A.SUBACCOUNT)
        GROUP BY A.SUBACCOUNT, A.TRANS_DUEDATE
    )
)
SELECT 'KIK'    AS TYPE, NVL(ABS(KIK.VD52136), 0)    AS AMT FROM KIK
UNION ALL
SELECT 'NONKIK' AS TYPE, NVL(ABS(NONKIK.VD52136), 0) AS AMT FROM NONKIK;