SELECT DECODE(TRANS_FLAG, '702', 'EFEK JASA KUSTODIAN CLIENT - KUSTODI KSEI - KUSTODI CITRA', TRANS_FLAG) AS TRANS_FLAG,
       NVL(SUM(TC.AMOUNTIDR), 0)                                    AS AMT
FROM MKBD.MKBD_FINAL_TRADES TC
WHERE TC.GEN_DATE = TO_DATE('2026-04-21', 'YYYY-MM-DD')
  AND TC.SOURCE_ID IN ('527')
GROUP BY TRANS_FLAG