SELECT TL.ACCOUNT, A.NAME, TL.AMOUNTIDR
FROM MKBD.MKBD_FINAL_JOURNAL TL,
     DENPASAR.ACCOUNT A
WHERE TL.GEN_DATE = TO_DATE('2026-04-21', 'YYYY-MM-DD')
  AND A.CODE = TL.ACCOUNT
  AND SOURCE_ID IN ('702', '703', '704', '705', '706')