SELECT
            ACCOUNT, NVL(SUM(ENDBAL_DEBIT + ENDBAL_CREDIT), 0) AS AMOUNT
            FROM MKBD.MKBD_BALANCE_SUMMARY
            WHERE GEN_DATE = TO_DATE('2026-04-21', 'yyyy-mm-dd')
              AND ACCOUNT IN ('30201001', '30202001')
              AND LENGTH(ACCOUNT) = 8
              AND MKBD_FLAG = 0
GROUP BY ACCOUNT
ORDER BY ACCOUNT