SELECT BRK_COD1                         AS BUYING_BROKER,
       BRK_COD2                         AS SELLING_BROKER,
       SUM(NVL(STK_VOLM * STK_PRIC, 0)) AS AMT
FROM DENPASAR.EXCHANGE_TRANSACTION_DATA
WHERE TRX_DATE <= TO_DATE(:genDate, 'yyyy-mm-dd')
  AND TRX_TYPE = 'NG'
  AND BRK_COD2 != BRK_COD1
  AND BRK_COD1 = 'KI'
  AND SETTLEDATE > TO_DATE(:genDate, 'yyyy-mm-dd')
GROUP BY BRK_COD2, BRK_COD1
ORDER BY BRK_COD2, BRK_COD1