WITH ELIGIBLE_SUBACCOUNT AS (
    -- subaccount yang masuk filter: net < 0 AND client INTEREST_AGRREMENT = 1
    SELECT A.SUBACCOUNT, ABS(SUM(A.AMOUNTIDR)) AS AMOUNTIDR
    FROM (
        SELECT ACCOUNT, SUBACCOUNT, SUM(AMOUNTIDR) AS AMOUNTIDR
        FROM (
            SELECT L.ACCOUNT, L.SUBACCOUNT, SUM(L.AMOUNTIDR) AS AMOUNTIDR
            FROM DENPASAR.LEDGER_HISTORICAL@cammon L
            INNER JOIN DENPASAR.ACCOUNT A ON L.ACCOUNT = A.CODE
            WHERE L.TRANS_PERIOD    = TO_CHAR(TO_DATE(:genDate,'yyyy-mm-dd'),'yyyymm')
              AND L.TRANS_CURRENT   = 0
              AND A.SUBACCOUNT_TYPE > 0
              AND L.ACCOUNT IN ('10401021','10401022','10401031','10401071','10401131')
              AND L.TRANS_DUEDATE  <= TO_DATE(:genDate,'yyyy-mm-dd')
              AND L.GEN_DATE        = TO_DATE(:genDate,'yyyy-mm-dd')
            GROUP BY L.ACCOUNT, L.SUBACCOUNT
            UNION ALL
            SELECT ACCOUNT, SUBACCOUNT, SUM(AMOUNTIDR)
            FROM DENPASAR.LEDGER_HISTORICAL@cammon
            WHERE ACCOUNT IN ('10401021','10401022','10401031','10401071','10401131')
              AND TRANS_DATE    >= TRUNC(TO_DATE(:genDate,'yyyy-mm-dd'),'MM')
              AND TRANS_DUEDATE <= TO_DATE(:genDate,'yyyy-mm-dd')
              AND TRANS_CURRENT  > 0
              AND GEN_DATE       = TO_DATE(:genDate,'yyyy-mm-dd')
            GROUP BY ACCOUNT, SUBACCOUNT
        )
        GROUP BY ACCOUNT, SUBACCOUNT
        HAVING SUM(AMOUNTIDR) < 0
    ) A
    INNER JOIN DENPASAR.CLIENT_PROPERTY B ON A.SUBACCOUNT = B.CLIENT_ID
    WHERE B.INTEREST_AGRREMENT = 1
    GROUP BY A.SUBACCOUNT
)
SELECT
    L.ACCOUNT,
    L.SUBACCOUNT,
    CASE L.TRANS_CURRENT
        WHEN 0 THEN 'OPENING'
        ELSE        'CURRENT'
    END AS TRANS_CURRENT_LABEL,
    SUM(L.AMOUNTIDR) AS AMOUNTIDR
FROM DENPASAR.LEDGER_HISTORICAL@cammon L
INNER JOIN DENPASAR.ACCOUNT A ON L.ACCOUNT = A.CODE
INNER JOIN ELIGIBLE_SUBACCOUNT E ON L.SUBACCOUNT = E.SUBACCOUNT
WHERE L.TRANS_PERIOD    = TO_CHAR(TO_DATE(:genDate,'yyyy-mm-dd'),'yyyymm')
  AND A.SUBACCOUNT_TYPE > 0
  AND L.ACCOUNT IN ('10401021','10401022','10401031','10401071','10401131')
  AND L.GEN_DATE        = TO_DATE(:genDate,'yyyy-mm-dd')
  AND (
          (L.TRANS_CURRENT = 0 AND L.TRANS_DUEDATE <= TO_DATE(:genDate,'yyyy-mm-dd'))
       OR (L.TRANS_CURRENT > 0
           AND L.TRANS_DATE    >= TRUNC(TO_DATE(:genDate,'yyyy-mm-dd'),'MM')
           AND L.TRANS_DUEDATE <= TO_DATE(:genDate,'yyyy-mm-dd'))
      )
GROUP BY L.ACCOUNT, L.SUBACCOUNT, L.TRANS_CURRENT
ORDER BY L.SUBACCOUNT, L.ACCOUNT, L.TRANS_CURRENT;