SELECT DECODE(TRANS_FLAG, '913', 'Client Portfolio', TRANS_FLAG) AS TRANS_FLAG,
       NVL(SUM(TC.AMOUNTIDR), 0)                                    AS AMT
FROM MKBD.MKBD_FINAL_TRADES TC
WHERE TC.GEN_DATE = TO_DATE(:genDate, 'YYYY-MM-DD')
  AND TC.SOURCE_ID IN ('640')
GROUP BY TRANS_FLAG
