server:
  port: 9090
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,application/xml,text/html,text/plain

spring:
  application:
    name: mkbd_master_menu

  threads:
    virtual:
      enable: true

  oracle:
    datasource:
      url: jdbc:oracle:thin:@10.10.1.173:1521:DEVDBA
      username: denpasar
      password: password
      driverClassName: oracle.jdbc.OracleDriver
      hikari:
        maximum-pool-size: 5  # Increased pool size for better concurrency
        minimum-idle: 1        # More idle connections for quick response
        idle-timeout: 30000  # Reduced to 30 seconds
        pool-name: ORACLE_BO_HIKARI_CP
        connection-timeout: 20000  # Reduced to 20 seconds
        max-lifetime: 900000       # Reduced to 15 minutes
        leak-detection-threshold: 30000  # Reduced to 2 seconds for more immediate detection
        connection-test-query: SELECT 1 FROM DUAL
        auto-commit: false        # Ensure transactions are explicitly committed
        validation-timeout: 5000   # Timeout for connection validation
    jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: none
        format-sql: true
        batch-size: 5000
      properties:
        hibernate.jdbc.lob.non_contextual_creation: true  # Fix for LOB issues
        hibernate.order_updates: true  # Optimize update queries
        hibernate.order_inserts: true  # Optimize insert queries

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari.HikariDataSource: DEBUG
    oracle.jdbc: TRACE

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /docs.html
