SELECT TL.TRANS_FLAG,
       TL.TRANS_MODULE,
       TL.TRANS_NO,
       TL.TRANS_DATE,
       TL.TRANS_DUEDATE,
       TL.NSHARE,
       TL.ACCOUNT,
       NVL(A.NAME, NVL(TL.ACCOUNT, '-')) AS ACCOUNT_NAME,
       TL.SUBACCOUNT,
       NVL(C.NAME, NVL(TL.SUBACCOUNT, '-')) AS CLIENT_NAME,
       TL.DESCRIPTION,
       TL.CURRENCY,
       TL.AMOUNT,
       TL.EXCHANGERATE,
       TL.AMOUNTIDR
FROM MKBD.MKBD_FINAL_JOURNAL TL
INNER JOIN DENPASAR.ACCOUNT A ON A.CODE = TL.ACCOUNT
LEFT JOIN DENPASAR.CLIENT C ON TL.SUBACCOUNT = C.CODE
WHERE TL.GEN_DATE = TO_DATE(:genDate, 'YYYY-MM-DD')
  AND TL.SOURCE_ID IN ('702', '703', '704', '705', '706')