SELECT M.ACCOUNT,
       NVL(A.NAME, NVL(M.ACCOUNT, '-')) AS ACCOUNT_NAME,
       NVL(SUM(M.ENDBAL_DEBIT + M.ENDBAL_CREDIT), 0) AS AMT
FROM MKBD.MKBD_BALANCE_SUMMARY M
LEFT JOIN DENPASAR.ACCOUNT A ON M.ACCOUNT = A.CODE
WHERE M.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND M.ACCOUNT IN ('10601011', '10601021', '10601031', '10601041')
  AND LENGTH(M.ACCOUNT) = 8
  AND M.MKBD_FLAG = 0
GROUP BY M.ACCOUNT, A.NAME
ORDER BY M.ACCOUNT