SELECT
                ACCOUNT, NVL(SUM(ENDBAL_DEBIT + ENDBAL_CREDIT), 0) AS AMT
            FROM MKBD.MKBD_BALANCE_SUMMARY
            WHERE GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
              AND ACCOUNT IN ('10601011', '10601021', '10601031', '10601041')
              AND LENGTH(ACCOUNT) = 8
              AND MKBD_FLAG = 0
GROUP BY ACCOUNT
ORDER BY ACCOUNT