SELECT SP.NCLIENT AS NCLIENT,
       NVL(SP.NCLIENT, '-') AS ISIN_NAME,
       SUM(SP.MARKET_VALUE) AS VAL
FROM MKBD.MKBD_PORTFOLIO_HAIRCUT SP
WHERE SP.RECDATE = TO_DATE(:genDate, 'YYYY-MM-DD')
GROUP BY SP.NCLIENT

UNION ALL

SELECT R.NSHARE_NAME AS NCLIENT,
       NVL(I.NAME, NVL(R.NSHARE_NAME, '-')) AS ISIN_NAME,
       SUM(R.TOTAL_NAB) AS VAL
FROM MKBD.RDAUM_CONCENTRATION_RISK R
LEFT JOIN MKBD.ISINCODE I
       ON I.ISINCODE = R.NSHARE_NAME
      AND I.ISINTYPE = 'REKSADANA'
WHERE R.GEN_DATE = TO_DATE(:genDate, 'YYYY-MM-DD')
GROUP BY R.NSHARE_NAME, I.NAME