SELECT DECODE(TRANS_FLAG, '831', 'LEDGER NG-PT Non KI', TRANS_FLAG) AS TRANS_FLAG,
       NVL(SUM(TC.AMOUNTIDR), 0)                                    AS AMT
FROM MKBD.MKBD_FINAL_TRADES TC
WHERE TC.GEN_DATE = TO_DATE(:genDate, 'YYYY-MM-DD')
  AND TC.SOURCE_ID IN ('684', '647')
GROUP BY TRANS_FLAG