SELECT
    'PORTFOLIO_HAIRCUT'  AS SOURCE,
    SP.NCLIENT           AS GROUP_KEY,
    NVL(S.NAME, SP.NSHARE)               AS NSHARE_NAME,
    SP.MARKET_VALUE      AS TOTAL_NAB,
    SP.MARKET_VALUE      AS CONTRIB_TO_VAL,
    SP.RECDATE           AS REC_DATE
FROM MKBD.MKBD_PORTFOLIO_HAIRCUT SP
LEFT JOIN DENPASAR.SHARES S
       ON S.CODE = SP.NSHARE
WHERE SP.RECDATE = TO_DATE(:genDate, 'YYYY-MM-DD')

UNION ALL

SELECT
    'RDAUM_CONCENTRATION'      AS SOURCE,
    R.NSHARE_NAME              AS GROUP_KEY,
    NVL(I.NAME, R.NSHARE_NAME)                     AS NSHARE_NAME,
    R.TOTAL_NAB,
    R.TOTAL_NAB                AS CONTRIB_TO_VAL,
    R.GEN_DATE                 AS REC_DATE
FROM MKBD.RDAUM_CONCENTRATION_RISK R
LEFT JOIN MKBD.ISINCODE I
       ON I.ISINCODE = R.NSHARE_NAME
      AND I.ISINTYPE = 'REKSADANA'
WHERE R.GEN_DATE = TO_DATE(:genDate, 'YYYY-MM-DD')
ORDER BY SOURCE, GROUP_KEY;