SELECT TC.TRANS_FLAG,
       TC.TRANS_MODULE,
       TC.TRANS_NO,
       TC.TRANS_DATE,
       TC.TRANS_DUE,
       TC.ACCOUNT,
       NVL(CA.NAME, NVL(TC.ACCOUNT, '-')) AS CUSTODY_NAME,
       TC.NCLIENT,
       NVL(C.NAME, NVL(TC.NCLIENT, '-')) AS CLIENT_NAME,
       TC.NSHARE,
       TC.QUANTITY,
       TC.CURRENCY,
       TC.PRICE,
       TC.AMOUNT,
       TC.EXCHANGERATE,
       TC.AMOUNTIDR
FROM MKBD.MKBD_FINAL_TRADES TC
LEFT JOIN DENPASAR.CUSTODY_ACCOUNT CA ON TC.ACCOUNT = CA.CODE
LEFT JOIN DENPASAR.CLIENT C ON TC.NCLIENT = C.CODE
WHERE TC.GEN_DATE = TO_DATE(:genDate, 'YYYY-MM-DD')
  AND TC.SOURCE_ID IN ('653')