SELECT DECODE(TRANS_FLAG, '911', 'KUSTODI KSEI (SAHAM LOKAL - HOUSE) - SAHAM DELISTING - NASABAH SERAH', TRANS_FLAG) AS TRANS_FLAG,
       NVL(SUM(TC.AMOUNTIDR), 0)                                    AS AMT
FROM MKBD.MKBD_FINAL_TRADES TC
WHERE TC.GEN_DATE = TO_DATE(:genDate, 'YYYY-MM-DD')
  AND TC.SOURCE_ID IN ('655')
GROUP BY TRANS_FLAG