SELECT DECODE(TRANS_FLAG, '702', 'KUSTODI CITRA', '912', 'KUSTODI KSEI (Regular - Non House - Exclude PORTFOLIO REPO) - SAHAM DELISTING - NASABAH SERAH', TRANS_FLAG) AS TRANS_FLAG,
       NVL(SUM(TC.AMOUNTIDR), 0)                                    AS AMT
FROM MKBD.MKBD_FINAL_TRADES TC
WHERE TC.GEN_DATE = TO_DATE(:genDate, 'YYYY-MM-DD')
  AND TC.SOURCE_ID IN ('644', '631')
GROUP BY TRANS_FLAG