SELECT
    TO_DATE(:genDate, 'yyyy-mm-dd') AS RECDATE,
    CU.NCLIENT,
    CU.NSHARE,
    CU.TRANS_PERIOD,
    CU.TRANS_DATE,
    CU.GEN_DATE,
    CU.PRICE,
    CU.QUANTITY,
    CASE
        WHEN CU.TRANS_PERIOD = '622' THEN CU.PRICE
        ELSE NVL(CP.CLOSINGPRICE, 1)
    END                         AS CLOSING_PRICE,
    CU.QUANTITY * CP.CLOSINGPRICE AS MVAL,
    CASE
        WHEN H.CODE IS NULL THEN 85
        WHEN NVL(H.MKBD, 0) <= 0 THEN 0
        ELSE H.MKBD
    END                         AS HAIRCUTMKBD
FROM MKBD.MKBD_COMPILED_TRADES CU
LEFT JOIN MKBD.HAIRCUT H
       ON CU.NSHARE = H.CODE
LEFT JOIN DENPASAR.CLOSING_PRICE CP
       ON CU.NSHARE = CP.NSHARE
      AND CP.TANGGAL = TRUNC(TO_DATE(:genDate, 'yyyy-mm-dd'))
WHERE CU.TRANS_PERIOD = '621'
  AND CU.TRANS_DATE  <= TO_DATE(:genDate, 'yyyy-mm-dd')
  AND CU.GEN_DATE     = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND NVL(CP.CLOSINGPRICE, 0) > 0
ORDER BY CU.NCLIENT, CU.NSHARE, CU.TRANS_DATE;