WITH ELIGIBLE_SUBACCOUNTS AS (
    SELECT SUBACCOUNT, SUM(AMOUNTIDR) AS NET_AMOUNT
    FROM (
        SELECT L.SUBACCOUNT, SUM(L.AMOUNTIDR) AS AMOUNTIDR
        FROM DENPASAR.LEDGER_HISTORICAL@cammon L
        INNER JOIN DENPASAR.ACCOUNT A ON L.ACCOUNT = A.CODE
        WHERE L.TRANS_PERIOD = TO_CHAR(TO_DATE(:genDate, 'yyyy-mm-dd'), 'yyyymm')
          AND L.TRANS_DUEDATE <= TO_DATE(:genDate, 'yyyy-mm-dd')
          AND L.TRANS_CURRENT = 0
          AND L.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
          AND A.SUBACCOUNT_TYPE > 0
          AND L.ACCOUNT = '10401131'
        GROUP BY L.SUBACCOUNT

        UNION ALL

        SELECT SUBACCOUNT, SUM(AMOUNTIDR)
        FROM DENPASAR.LEDGER_HISTORICAL@cammon
        WHERE ACCOUNT = '10401131'
          AND (TRANS_DATE >= TRUNC(TO_DATE(:genDate, 'yyyy-mm-dd'), 'MM')
               AND TRANS_DUEDATE <= TO_DATE(:genDate, 'yyyy-mm-dd'))
          AND TRANS_CURRENT = 1
        AND GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
        GROUP BY SUBACCOUNT
    )
    GROUP BY SUBACCOUNT
    HAVING SUM(AMOUNTIDR) > 0
)
SELECT
    'OPENING'        AS SOURCE_BRANCH,
    L.ACCOUNT,
    L.SUBACCOUNT,
    L.TRANS_DATE,
    L.TRANS_DUEDATE,
    L.TRANS_PERIOD,
    L.TRANS_CURRENT,
    L.NFAKTUR,
    L.DESCRIPTION,
    L.NSHARE,
    L.BRANCH,
    L.CURRENCY,
    L.AMOUNTIDR
FROM DENPASAR.LEDGER_HISTORICAL@cammon L
INNER JOIN DENPASAR.ACCOUNT A        ON L.ACCOUNT    = A.CODE
INNER JOIN ELIGIBLE_SUBACCOUNTS ES   ON L.SUBACCOUNT = ES.SUBACCOUNT
WHERE L.TRANS_PERIOD = TO_CHAR(TO_DATE(:genDate, 'yyyy-mm-dd'), 'yyyymm')
  AND L.TRANS_DUEDATE <= TO_DATE(:genDate, 'yyyy-mm-dd')
  AND L.TRANS_CURRENT = 0
  AND L.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND A.SUBACCOUNT_TYPE > 0
  AND L.ACCOUNT = '10401131'

UNION ALL

SELECT
    'CURRENT'        AS SOURCE_BRANCH,
    L.ACCOUNT,
    L.SUBACCOUNT,
    L.TRANS_DATE,
    L.TRANS_DUEDATE,
    L.TRANS_PERIOD,
    L.TRANS_CURRENT,
    L.NFAKTUR,
    L.DESCRIPTION,
    L.NSHARE,
    L.BRANCH,
    L.CURRENCY,
    L.AMOUNTIDR
FROM DENPASAR.LEDGER_HISTORICAL@cammon L
INNER JOIN ELIGIBLE_SUBACCOUNTS ES ON L.SUBACCOUNT = ES.SUBACCOUNT
WHERE L.ACCOUNT = '10401131'
  AND TRANS_DATE    >= TRUNC(TO_DATE(:genDate, 'yyyy-mm-dd'), 'MM')
  AND TRANS_DUEDATE <= TO_DATE(:genDate, 'yyyy-mm-dd')
  AND L.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND TRANS_CURRENT = 1

ORDER BY SUBACCOUNT, SOURCE_BRANCH, TRANS_DATE, NFAKTUR