SELECT M.ACCOUNT,
       NVL(A.NAME, NVL(M.ACCOUNT, '-')) AS ACCOUNT_NAME,
       M.SUBACCOUNT_TYPE,
       M.SUBACCOUNT,
       NVL(C.NAME, NVL(M.SUBACCOUNT, '-')) AS CLIENT_NAME,
       M.BRANCH,
       M.CURRENCY,
       M.OPENBAL,
       M.DEBIT,
       M.CREDIT,
       M.ENDBAL,
       M.ENDBAL_DEBIT,
       M.ENDBAL_CREDIT,
       M.OPENBAL_DEBIT,
       M.OPENBAL_CREDIT
FROM MKBD.MKBD_BALANCE_SUMMARY M
LEFT JOIN DENPASAR.ACCOUNT A ON M.ACCOUNT = A.CODE
LEFT JOIN DENPASAR.CLIENT C ON M.SUBACCOUNT = C.CODE
WHERE M.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND M.ACCOUNT IN ('10901011', '10901021', '10704011', '10704021', '10490041')
  AND LENGTH(M.ACCOUNT) = 8
  AND M.MKBD_FLAG = 0