WITH MF_CLIENTS AS (
    SELECT CODE FROM DENPASAR.CLIENT WHERE SID LIKE 'MF%'
),
BASE_ROWS AS (
    SELECT
        A.ACCOUNT,
        A.SUBACCOUNT,
        A.TRANS_DATE,
        A.TRANS_DUEDATE,
        A.TRANS_PERIOD,
        A.TRANS_CURRENT,
        A.TRANS_MODULE,
        A.NFAKTUR,
        A.DESCRIPTION,
        A.NSHARE,
        A.BRANCH,
        A.CURRENCY,
        A.AMOUNT,
        A.AMOUNTIDR,
        A.GEN_DATE,
        CASE WHEN M.CODE IS NOT NULL THEN 'KIK' ELSE 'NONKIK' END AS TYPE
    FROM DENPASAR.LEDGER_HISTORICAL@cammon A
    LEFT JOIN MF_CLIENTS M ON M.CODE = A.SUBACCOUNT
    WHERE A.ACCOUNT       = '10401021'
      AND A.TRANS_DUEDATE BETWEEN DENPASAR.CALCULATE_DUEDATE(TO_CHAR(TO_DATE(:genDate,'yyyy-mm-dd'),'yyyy-mm-dd'), 1)
                              AND DENPASAR.CALCULATE_DUEDATE(TO_CHAR(TO_DATE(:genDate,'yyyy-mm-dd'),'yyyy-mm-dd'), 2)
      AND A.TRANS_MODULE  = 20
      AND A.TRANS_PERIOD  = TO_CHAR(TO_DATE(:genDate,'yyyy-mm-dd'),'yyyymm')
      AND A.SUBACCOUNT    LIKE '17%'
      AND A.GEN_DATE      = TO_DATE(:genDate,'yyyy-mm-dd')
),
BASE_WITH_GROUP_NET AS (
    SELECT
        BR.*,
        SUM(BR.AMOUNT) OVER (PARTITION BY BR.SUBACCOUNT, BR.TRANS_DUEDATE) AS GROUP_NET_AMOUNT
    FROM BASE_ROWS BR
)
SELECT
    BG.TYPE,
    BG.ACCOUNT,
    NVL(AC.NAME, NVL(BG.ACCOUNT, '-')) AS ACCOUNT_NAME,
    BG.SUBACCOUNT,
    NVL(CL.NAME, NVL(BG.SUBACCOUNT, '-')) AS CLIENT_NAME,
    BG.TRANS_DATE,
    BG.TRANS_DUEDATE,
    BG.TRANS_PERIOD,
    BG.TRANS_CURRENT,
    BG.TRANS_MODULE,
    BG.NFAKTUR,
    BG.DESCRIPTION,
    BG.NSHARE,
    BG.BRANCH,
    CASE
        WHEN BG.TYPE = 'KIK'    AND BG.AMOUNT > 0           THEN BG.AMOUNT
        WHEN BG.TYPE = 'NONKIK' AND BG.GROUP_NET_AMOUNT > 0 THEN BG.AMOUNT
    END AS NET_AMOUNT
FROM BASE_WITH_GROUP_NET BG
LEFT JOIN DENPASAR.ACCOUNT AC ON BG.ACCOUNT = AC.CODE
LEFT JOIN DENPASAR.CLIENT CL  ON BG.SUBACCOUNT = CL.CODE
WHERE (BG.TYPE = 'KIK'    AND BG.AMOUNT > 0)
   OR (BG.TYPE = 'NONKIK' AND BG.GROUP_NET_AMOUNT > 0)
ORDER BY BG.TYPE, BG.SUBACCOUNT, BG.TRANS_DUEDATE, BG.TRANS_DATE, BG.NFAKTUR