SELECT TO_CHAR(S.ACCOUNT) AS ACCOUNT,
       NVL(ACC.NAME, NVL(TO_CHAR(S.ACCOUNT), '-')) AS ACCOUNT_NAME,
       SUM(S.ENDBAL_DEBIT) AS BALANCE
FROM MKBD.MAP_BANK MB
INNER JOIN MKBD.MKBD_BALANCE_SUMMARY S ON S.ACCOUNT = MB.NCLIENT
INNER JOIN DENPASAR.ACCOUNT ACC        ON ACC.CODE = S.ACCOUNT
WHERE S.GEN_DATE        = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND LENGTH(MB.NCLIENT)   = 8
  AND LENGTH(MB.BANK_NAME) = 3
  AND MB.ISCLIENT          = 'N'
  AND ACC.ACCOUNT_TYPE     = (SELECT ID FROM DENPASAR.ACCOUNT_TYPE WHERE NAME = 'BANK')
GROUP BY S.ACCOUNT, ACC.NAME

UNION ALL

SELECT TO_CHAR(M.ACCOUNT) AS ACCOUNT,
       NVL(A.NAME, NVL(TO_CHAR(M.ACCOUNT), '-')) AS ACCOUNT_NAME,
       SUM(M.ENDBAL_DEBIT + M.ENDBAL_CREDIT) AS BALANCE
FROM MKBD.MKBD_BALANCE_SUMMARY M
LEFT JOIN DENPASAR.ACCOUNT A ON M.ACCOUNT = A.CODE
WHERE M.GEN_DATE       = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND LENGTH(M.ACCOUNT) = 8
  AND M.MKBD_FLAG       = 0
  AND M.ACCOUNT LIKE '10101%'
GROUP BY M.ACCOUNT, A.NAME

UNION ALL

SELECT '207 - FINAL BALANCE' AS ACCOUNT,
       '207 - FINAL BALANCE' AS ACCOUNT_NAME,
       -SUM(ABS(AP.AMOUNT)) AS BALANCE
FROM MKBD.MKBD_CLIENT_POSITION AP
INNER JOIN DENPASAR.CLIENT C           ON AP.NCLIENT = C.CODE
LEFT  JOIN DENPASAR.CLIENT_PROPERTY CP ON AP.NCLIENT = CP.CLIENT_ID
WHERE AP.TRANS_FLAG = 207
  AND AP.AMOUNT     < 0
  AND AP.GEN_DATE   = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND (LENGTH(NVL(CP.BANK_ACC_NO_INVESTOR, '')) < 1 OR CP.BANK_ACC_NO_INVESTOR IS NULL)
  AND C.CLIENT_TYPE IN (12, 14, 16, 33)