SELECT M.ACCOUNT,
       NVL(A.NAME, NVL(M.ACCOUNT, '-')) AS ACCOUNT_NAME,
       SUM(M.ENDBAL_DEBIT + M.ENDBAL_CREDIT) AS BALANCE
FROM MKBD.MKBD_BALANCE_SUMMARY M
LEFT JOIN DENPASAR.ACCOUNT A ON M.ACCOUNT = A.CODE
WHERE M.GEN_DATE = TO_DATE(:genDate, 'yyyy-mm-dd')
  AND LENGTH(M.ACCOUNT) = 8
  AND M.MKBD_FLAG = 0
  AND M.ACCOUNT LIKE '10101%'
GROUP BY M.ACCOUNT, A.NAME
ORDER BY M.ACCOUNT